forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length


class LoginForm(FlaskForm):
    username = StringField(validators=[
        InputRequired(),
        Length(min=4, max=20),
    ],
        render_kw={"placeholder": "Username"})

    password = PasswordField(validators=[
        InputRequired(),
        Length(min=4, max=20),
    ],
        render_kw={"placeholder": "Password"})

    submit = SubmitField("Login")

forms/sign_up_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError

from models.user import User 


class SignUpForm(FlaskForm):
    username = StringField(validators=[
        InputRequired(),
        Length(min=4, max=20),
    ],
        render_kw={"placeholder": "Username"})

    password = PasswordField(validators=[
        InputRequired(),
        Length(min=4, max=20),
    ],
        render_kw={"placeholder": "Password"})

    submit = SubmitField("Register")

    def validate_username(self, username):
        existing_user_username = User.query.filter_by(
            username=username.data).first()

        if existing_user_username:
            raise ValidationError(
                "That username already exists! Please choose a different one")

main.py
from app import app
from login_manager import LoginManager
from database import db
from hash import flask_bcrypt

from views import blueprint


app.register_blueprint(blueprint)

views.py
from flask import render_template, redirect, url_for, Blueprint, current_app

# Flask Login
from flask_login import login_required, login_user, logout_user, current_user

from database import db
from oauth import oauth
from hash import flask_bcrypt

from forms.login_form import LoginForm
from forms.sign_up_form import SignUpForm

from models.user import User, LocalUser

blueprint = Blueprint('views', __name__)

# TODO: Add configuration possibilities for needed user parameters


@blueprint.route("/")
def welcome():
    return render_template("main.html")


@blueprint.route("/signup", methods=["GET", "POST"])
def signup():
    form = SignUpForm()

    if not form.validate_on_submit():
        return render_template("signup.html", form=form)

    User.create_local_user(
        username=form.username.data,
        password=form.password.data
    )
    db.session.commit()

    return redirect(url_for("views.login"))


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if not form.validate_on_submit():
        return render_template("login.html", form=form)

    local_user = LocalUser.query.join(LocalUser.user).filter_by(
        username=form.username.data,
    ).first()

    if not local_user or not flask_bcrypt.check_password_hash(local_user.password, form.password.data):
        return render_template("login.html", form=form)

    login_user(local_user.user)
    return redirect(url_for("views.protected"))


@blueprint.route("/logout", methods=["GET", "POST"])
def logout():
    logout_user()

    return redirect(url_for("views.welcome"))


@blueprint.route("/delete", methods=["POST"])
def delete_account():
    db.session.delete(current_user)
    db.session.commit()

    return redirect(url_for("views.welcome"))


@blueprint.route("/signup/<provider>")
def signup_oidc(provider):
    redirect_url = url_for("views.authorize_signup_oidc",
                           _external=True, provider=provider)
    client = oauth.create_client(provider)

    if not client:
        return

    return client.authorize_redirect(redirect_url)


@blueprint.route("/signup/<provider>/authorize")
def authorize_signup_oidc(provider):
    client = oauth.create_client(provider)
    if not client:
        return

    token = client.authorize_access_token()
    print(f"{token}")

    user_info = token['userinfo']
    user = User.query.join(User.connected_providers).filter_by(
        sub=user_info.sub).first()
    if user:
        return redirect(url_for("views.login_oidc", provider=provider))

    # TODO: Use configuration
    # TODO: Add possibility to use plugin hooks for edge cases
    properties_to_map = current_app.config['OIDC_PROVIDER_PROPERTIES_TO_MAP']
    provider_configuration = current_app.config['OIDC_PROVIDER']
    corresponding_configuration = next(
        (configuration for configuration in provider_configuration if configuration['providerName'] == provider), None)
    mapped_values = {}

    for property in properties_to_map:
        property_configuration = corresponding_configuration[property]
        if type(property_configuration) is dict:
            property_values = []
            for property_name in property_configuration['fields']:
                property_values.append(user_info[property_name])

            mapped_value = property_configuration['separator'].join(
                property_values)
        else:
            mapped_value = user_info[property_configuration]

        mapped_values[property] = mapped_value

    user = User.create_oidc_account(
        user_property_values=mapped_values, provider=user_info['iss'], sub=user_info['sub'])
    db.session.commit()

    login_user(user)
    return redirect(url_for("views.protected"))


@blueprint.route("/login/<provider>")
def login_oidc(provider):
    redirect_url = url_for("views.authorize_login_oidc",
                           _external=True, provider=provider)

    return oauth.create_client(provider).authorize_redirect(redirect_url)


@blueprint.route("/login/<provider>/authorize")
def authorize_login_oidc(provider):
    client = oauth.create_client(provider)
    token = client.authorize_access_token()

    print(f"\nToken: {token}\n")
    user_info = token['userinfo']

    user = User.query.join(User.connected_providers).filter_by(
        provider=user_info['iss'], sub=user_info['sub']).first()
    if not user:
        return redirect(url_for("views.signup"))

    login_user(user)
    return redirect(url_for("views.protected"))


@blueprint.route("/protected")
@login_required
def protected():
    connected_providers = current_user.connected_providers.all()
    provider_configuration = current_app.config['OIDC_PROVIDER']

    ui_providers = []
    for provider in provider_configuration:
        provider_name = provider["providerName"]
        ui_provider = {
            'name': provider_name.capitalize()
        }

        if not next((connected_provider for connected_provider in connected_providers if connected_provider.provider == provider_name), None):
            ui_provider['text'] = "Connect"
            ui_provider['href'] = url_for(
                'views.connect_provider', provider=provider_name)
        else:
            ui_provider['text'] = "Disonnect"
            ui_provider['href'] = url_for(
                'views.disconnect_oidc', provider=provider_name)

        ui_providers.append(ui_provider)

    return render_template(
        "protected.html",
        providers=ui_providers
    )


@blueprint.route("/connect/<provider>")
@login_required
def connect_provider(provider):
    redirect_url = url_for("views.authorize_connect_oidc",
                           _external=True, provider=provider)
    client = oauth.create_client(provider)

    if not client:
        return

    return client.authorize_redirect(redirect_url)


@blueprint.route("/connect/<provider>/authorize")
@login_required
def authorize_connect_oidc(provider):
    client = oauth.create_client(provider)
    token = client.authorize_access_token()

    print(f"\nToken: {token}\n")

    user_info = token['userinfo']
    current_user.connect_oidc_provider(provider, user_info.sub)
    db.session.commit()

    return redirect(url_for("views.protected"))


@blueprint.route("/disconnect/<provider>")
@login_required
def disconnect_oidc(provider):
    client = oauth.create_client(provider)
    if not client:
        return redirect(url_for("views.protected"))

    current_user.disconnect_oidc_provider(provider)
    db.session.commit()

    return redirect(url_for("views.protected"))

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>

<body>
    <h1>Login</h1>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ form.username }}
        {{ form.password }}
        {{ form.submit }}
    </form>

    <br />

    <button><a href="{{url_for('views.login_oidc', provider='google')}}">Login using Google</a></button>
    <button><a href="{{url_for('views.login_oidc', provider='microsoft')}}">Login using Microsoft (works only if
            accessed via
            localhost)</a></button>
    <button><a href="{{url_for('views.login_oidc', provider='orcid')}}">Login using ORCID</a></button>
    <button><a href="{{url_for('views.login_oidc', provider='gitlab')}}">Login using Gitlab</a></button>
</body>

</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Flask OAuth Tests</title>
</head>

<body>
    <h1>Welcome to my Test Application!</h1>

    <a href="{{url_for('views.login')}}">Login</a>
    <a href="{{url_for('views.signup')}}">Sign Up</a>
</body>

templates/protected.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Flask OAuth Tests</title>
</head>

<body>
    <h1>Welcome {{ current_user.username }}!</h1>

    <h2>Connected Providers</h2>

    <table>
        {%for provider in providers%}
        <tr>
            <td>{{ provider.name }}</td>
            <td><Button><a
                        href="{{provider.href}}">{{provider.text}}</a></Button>
            </td>
        </tr>
        {%endfor%}
    </table>

    <br />
    <br />

    <button><a href="{{url_for('views.logout')}}">Logout</a></button>

    <form action="{{url_for('views.delete_account', user_id=current_user.id)}}" method="post">
        <button name="delete">Delete Account</button>
    </form>
</body>

</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Sing Up</title>
</head>

<body>
    <h1>Sing Up</h1>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ form.username }}
        {{ form.password }}
        {{ form.submit }}
    </form>

    <br />

    <button><a href="{{url_for('views.signup_oidc', provider='google')}}">Signup using Google</a></button>

    <button><a href="{{url_for('views.signup_oidc', provider='microsoft')}}">Signup using Microsoft (works only if
            accessed via
            localhost)</a></button>

    <button><a href="{{url_for('views.signup_oidc', provider='orcid')}}">Signup using ORCID</a></button>

    <button><a href="{{url_for('views.signup_oidc', provider='gitlab')}}">Signup using Gitlab</a></button>

    <br />

    Already have an account? <a href="{{url_for('views.login')}}">Login</a>
</body>

</html>